
server:
  port: 7001


  # 需要在host文件中添加映射 C:\Windows\System32\drivers\etc\host
  # 127.0.0.1 eureka7001

eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # 表示自己就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/